version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: Hello7710
      POSTGRES_USER: pricepirate
      POSTGRES_DB: stonks
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
